export const instrumentImages = {
  "Flauti I II":          "chartreuse_flute.png",
  "Oboi I II":            "scarlet_oboe.png",
  "Clarinetti in B I II": "periwinkle_clarinet.png",
  "Fagotti I II":         "indigo_bassoon.png",
  "Corno I in F":         "red_trumpet.png",
  "Corno II in F":        "red_trumpet.png",
  "Violino I":            "vermilion_violin.png",
  "Violino II":           "vermilion_violin.png",
  "Viola":                "saffron_viola.png" ,
  "Violoncello":          "violet_cello.png",
  "Contrabasso":          "cerulean_bass.png",
  "Double Basses": "cerulean_bass.png",
  "Soprano solo": "chartreuse_flute.png",
  "Alto solo": "periwinkle_clarinet.png",
  "Tenor solo": "red_trumpet.png",
  "Baritono Solo": "indigo_bassoon.png",
  "Coro": "red_trumpet.png",
  "soprano": "chartreuse_flute.png",
  "Alto": "periwinkle_clarinet.png",
  "Tenor": "red_trumpet.png",
  "Baritono Coro": "violet_cello.png",
};


export const instrumentCommonNames = {
  "Flauti I II":          "Flute",
  "Oboi I II":            "Oboe 1 & 2",
  "Clarinetti in B I II": "Clarinet 1 & 2",
  "Fagotti I II":         "Bassoon 1 & 2",
  "Corno I in F":         "Horn 1",
  "Corno II in F":        "Horn 2",
  "Violino I":            "Violin 1",
  "Violino II":           "Violin 2",
  "Viola":                "Viola" ,
  "Violoncello":          "Cello",
  "Contrabasso":          "Double Bass",
  "Double Basses": "Double Bass",
  "Soprano solo": "Soprano Soloist",
  "Alto solo": "Alto Soloist",
  "Tenor solo": "Tenor Soloist",
  "Baritono Solo": "Baritone Soloist",
  "Coro": "Chorus",
  "soprano": "Sopranos",
  "Alto": "Altos",
  "Tenor": "Tenors",
  "Baritono Coro": "Baritones",
};
